export const sampleScan = {
  meta: {
    scan_name: 'NC/RDU Digital Health + Health Transformation',
    generated_at: new Date().toISOString(),
    query: 'Demo scan using built-in examples. Connect OPENAI_API_KEY for live search.',
    scope: 'NC/RDU, digital health, health transformation, 50-1000 employees',
    methodology: 'Scored using Bluedoor Customer Signal weights: leadership change, ICP fit, funding momentum, hiring velocity, and strategic fit.'
  },
  summary: {
    executive_brief: 'Demo results show how the BI layer prioritizes companies with commercial inflection signals, leadership changes, funding momentum, and a clear Bluedoor package wedge.',
    total_companies_found: 7,
    hot_leads: 3,
    average_score: 78,
    strongest_pattern: 'Digital health companies moving from product validation into GTM scale need sharper buyer journeys, enablement, customer evidence, and category narrative.'
  },
  companies: [
    {
      company: 'Validic',
      website: 'https://validic.com',
      hq: 'Durham, NC',
      employee_range: '51-200',
      stage: 'Growth / PE-backed',
      sector: 'Remote monitoring and healthcare data connectivity',
      signal_type: 'Commercial expansion + enterprise buyer complexity',
      signal_date: 'Demo',
      signal_summary: 'Strong fit for enterprise buyer journey and value narrative work because the company sells into complex provider, payer, and device ecosystems.',
      funding_momentum_score: 14,
      leadership_signal_score: 31,
      hiring_velocity_score: 16,
      icp_fit_score: 18,
      strategic_fit_score: 9,
      total_score: 88,
      priority: 'Hot',
      package_map: 'Buyer Journey Map + Sales Enablement Portfolio',
      why_it_matters: 'The value proposition requires multiple stakeholders to understand workflow, ROI, interoperability, and clinical adoption.',
      recommended_first_outreach: 'Lead with a note about translating remote-monitoring value into enterprise buyer journeys and sales enablement by ICP.',
      next_action: 'Research current commercial leadership and open GTM roles.',
      confidence: 'Medium',
      caveats: 'Demo row. Replace with live evidence after API scan.',
      evidence_links: [
        { title: 'Company website', url: 'https://validic.com', source_type: 'Company site' }
      ]
    },
    {
      company: 'CareYaya',
      website: 'https://www.careyaya.org',
      hq: 'Raleigh-Durham, NC',
      employee_range: '51-200',
      stage: 'Growth',
      sector: 'Caregiving, aging, workforce innovation',
      signal_type: 'Category creation + channel expansion',
      signal_date: 'Demo',
      signal_summary: 'Strong category narrative and partnership enablement opportunity around student-powered caregiving and aging-in-place models.',
      funding_momentum_score: 12,
      leadership_signal_score: 28,
      hiring_velocity_score: 15,
      icp_fit_score: 19,
      strategic_fit_score: 10,
      total_score: 84,
      priority: 'Hot',
      package_map: 'Category Narrative + Buyer Journey Map',
      why_it_matters: 'The model sits between consumer care, health systems, workforce, and aging services, creating a need for clear buyer segmentation.',
      recommended_first_outreach: 'Anchor on helping CareYaya turn a compelling story into segmented buyer journeys for health systems, aging services, and partners.',
      next_action: 'Map likely buyers and partnership channels.',
      confidence: 'Medium',
      caveats: 'Demo row. Replace with live evidence after API scan.',
      evidence_links: [
        { title: 'Company website', url: 'https://www.careyaya.org', source_type: 'Company site' }
      ]
    },
    {
      company: 'Medicom Technologies',
      website: 'https://www.medicom.us',
      hq: 'Raleigh, NC',
      employee_range: '51-200',
      stage: 'Growth',
      sector: 'Medical imaging exchange and interoperability',
      signal_type: 'Enterprise workflow complexity',
      signal_date: 'Demo',
      signal_summary: 'Enterprise interoperability platform with a clear need for segmented messaging across imaging centers, providers, and health systems.',
      funding_momentum_score: 10,
      leadership_signal_score: 25,
      hiring_velocity_score: 14,
      icp_fit_score: 17,
      strategic_fit_score: 8,
      total_score: 74,
      priority: 'Qualified',
      package_map: 'Sales Enablement Portfolio',
      why_it_matters: 'Complex infrastructure buyers need proof, workflow mapping, and stakeholder-specific value stories.',
      recommended_first_outreach: 'Offer to map the imaging interoperability buying committee and create enablement assets by stakeholder.',
      next_action: 'Look for recent growth, partnership, or hiring signals.',
      confidence: 'Medium',
      caveats: 'Demo row. Replace with live evidence after API scan.',
      evidence_links: [
        { title: 'Company website', url: 'https://www.medicom.us', source_type: 'Company site' }
      ]
    },
    {
      company: 'Feedtrail',
      website: 'https://www.feedtrail.com',
      hq: 'Raleigh, NC',
      employee_range: '11-50',
      stage: 'Growth',
      sector: 'Patient experience and real-time feedback',
      signal_type: 'ICP caveat: smaller employee count',
      signal_date: 'Demo',
      signal_summary: 'Could fit Bluedoor if expanding enterprise sales, but employee-count threshold may make it a watchlist target.',
      funding_momentum_score: 8,
      leadership_signal_score: 18,
      hiring_velocity_score: 10,
      icp_fit_score: 13,
      strategic_fit_score: 8,
      total_score: 57,
      priority: 'Watchlist',
      package_map: 'Customer Evidence/ROI',
      why_it_matters: 'Patient experience platforms often need clearer ROI language for health system buyers.',
      recommended_first_outreach: 'Watch for funding, leadership hire, or enterprise expansion before outreach.',
      next_action: 'Monitor jobs and funding news.',
      confidence: 'Low',
      caveats: 'Employee range may fall below target threshold.',
      evidence_links: [
        { title: 'Company website', url: 'https://www.feedtrail.com', source_type: 'Company site' }
      ]
    },
    {
      company: 'Axil Health',
      website: 'https://www.axilhealth.com',
      hq: 'North Carolina',
      employee_range: '11-50',
      stage: 'Early growth',
      sector: 'Healthcare transformation / operations',
      signal_type: 'Early transformation wedge',
      signal_date: 'Demo',
      signal_summary: 'Relevant to health transformation, but likely earlier than the strongest Series A-C GTM scale profile.',
      funding_momentum_score: 7,
      leadership_signal_score: 22,
      hiring_velocity_score: 9,
      icp_fit_score: 14,
      strategic_fit_score: 9,
      total_score: 61,
      priority: 'Watchlist',
      package_map: 'Discovery Sprint',
      why_it_matters: 'Potential strategic fit if the company is packaging transformation offerings for enterprise buyers.',
      recommended_first_outreach: 'Lead with discovery and packaging, not a heavy sales-enablement motion yet.',
      next_action: 'Validate current headcount and commercial maturity.',
      confidence: 'Low',
      caveats: 'Demo row. Employee count and current activity require validation.',
      evidence_links: [
        { title: 'Company website', url: 'https://www.axilhealth.com', source_type: 'Company site' }
      ]
    },
    {
      company: 'Curi',
      website: 'https://www.curi.com',
      hq: 'Raleigh, NC',
      employee_range: '201-500',
      stage: 'Mature growth',
      sector: 'Physician services, advisory, insurance, wealth',
      signal_type: 'Strategic adjacency',
      signal_date: 'Demo',
      signal_summary: 'Not a pure digital health startup, but a strong healthcare-market intelligence and buyer segmentation candidate.',
      funding_momentum_score: 6,
      leadership_signal_score: 20,
      hiring_velocity_score: 11,
      icp_fit_score: 12,
      strategic_fit_score: 9,
      total_score: 58,
      priority: 'Watchlist',
      package_map: 'Buyer Journey Map',
      why_it_matters: 'Provider-facing offerings require segmented messaging across physician owners, executives, and practice leaders.',
      recommended_first_outreach: 'Only pursue if there is a new product launch, growth initiative, or leadership change.',
      next_action: 'Monitor leadership announcements and product launches.',
      confidence: 'Medium',
      caveats: 'Adjacent fit, not core digital health.',
      evidence_links: [
        { title: 'Company website', url: 'https://www.curi.com', source_type: 'Company site' }
      ]
    },
    {
      company: 'Compass Surgical Partners',
      website: 'https://compass-sp.com',
      hq: 'Raleigh, NC',
      employee_range: '51-200',
      stage: 'Growth',
      sector: 'ASC development and management',
      signal_type: 'Healthcare services expansion',
      signal_date: 'Demo',
      signal_summary: 'Healthcare services operator with enterprise growth needs, but less pure digital health fit.',
      funding_momentum_score: 9,
      leadership_signal_score: 23,
      hiring_velocity_score: 13,
      icp_fit_score: 11,
      strategic_fit_score: 7,
      total_score: 63,
      priority: 'Qualified',
      package_map: 'Sales Enablement Portfolio',
      why_it_matters: 'ASC growth requires clear physician, health-system, and investor-facing value narratives.',
      recommended_first_outreach: 'Frame around growth enablement and stakeholder-specific value stories for ASC expansion.',
      next_action: 'Validate current expansion plans and new leadership.',
      confidence: 'Medium',
      caveats: 'Healthcare services fit, not digital health core.',
      evidence_links: [
        { title: 'Company website', url: 'https://compass-sp.com', source_type: 'Company site' }
      ]
    }
  ]
};
